// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.4
// source: clientTransform.proto

package clientTransform

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientType int32

const (
	ClientType_LOCAL ClientType = 0
	ClientType_API   ClientType = 1
)

// Enum value maps for ClientType.
var (
	ClientType_name = map[int32]string{
		0: "LOCAL",
		1: "API",
	}
	ClientType_value = map[string]int32{
		"LOCAL": 0,
		"API":   1,
	}
)

func (x ClientType) Enum() *ClientType {
	p := new(ClientType)
	*p = x
	return p
}

func (x ClientType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientType) Descriptor() protoreflect.EnumDescriptor {
	return file_clientTransform_proto_enumTypes[0].Descriptor()
}

func (ClientType) Type() protoreflect.EnumType {
	return &file_clientTransform_proto_enumTypes[0]
}

func (x ClientType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientType.Descriptor instead.
func (ClientType) EnumDescriptor() ([]byte, []int) {
	return file_clientTransform_proto_rawDescGZIP(), []int{0}
}

type FileData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileUUID    string `protobuf:"bytes,1,opt,name=fileUUID,proto3" json:"fileUUID,omitempty"`
	FileContent []byte `protobuf:"bytes,2,opt,name=fileContent,proto3" json:"fileContent,omitempty"`
}

func (x *FileData) Reset() {
	*x = FileData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientTransform_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileData) ProtoMessage() {}

func (x *FileData) ProtoReflect() protoreflect.Message {
	mi := &file_clientTransform_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileData.ProtoReflect.Descriptor instead.
func (*FileData) Descriptor() ([]byte, []int) {
	return file_clientTransform_proto_rawDescGZIP(), []int{0}
}

func (x *FileData) GetFileUUID() string {
	if x != nil {
		return x.FileUUID
	}
	return ""
}

func (x *FileData) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

// pre-request, if the same uuid exists it is not uploaded
type FilePreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID   string     `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	ClientType ClientType `protobuf:"varint,2,opt,name=clientType,proto3,enum=clientProto.ClientType" json:"clientType,omitempty"`
	FileUUID   []string   `protobuf:"bytes,3,rep,name=fileUUID,proto3" json:"fileUUID,omitempty"`
}

func (x *FilePreRequest) Reset() {
	*x = FilePreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientTransform_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilePreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePreRequest) ProtoMessage() {}

func (x *FilePreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clientTransform_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePreRequest.ProtoReflect.Descriptor instead.
func (*FilePreRequest) Descriptor() ([]byte, []int) {
	return file_clientTransform_proto_rawDescGZIP(), []int{1}
}

func (x *FilePreRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *FilePreRequest) GetClientType() ClientType {
	if x != nil {
		return x.ClientType
	}
	return ClientType_LOCAL
}

func (x *FilePreRequest) GetFileUUID() []string {
	if x != nil {
		return x.FileUUID
	}
	return nil
}

// post request, upload the file content
type FilePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID   string      `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	ClientType ClientType  `protobuf:"varint,2,opt,name=clientType,proto3,enum=clientProto.ClientType" json:"clientType,omitempty"`
	LocalData  []*FileData `protobuf:"bytes,3,rep,name=localData,proto3" json:"localData,omitempty"`
}

func (x *FilePostRequest) Reset() {
	*x = FilePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientTransform_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePostRequest) ProtoMessage() {}

func (x *FilePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clientTransform_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePostRequest.ProtoReflect.Descriptor instead.
func (*FilePostRequest) Descriptor() ([]byte, []int) {
	return file_clientTransform_proto_rawDescGZIP(), []int{2}
}

func (x *FilePostRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *FilePostRequest) GetClientType() ClientType {
	if x != nil {
		return x.ClientType
	}
	return ClientType_LOCAL
}

func (x *FilePostRequest) GetLocalData() []*FileData {
	if x != nil {
		return x.LocalData
	}
	return nil
}

type FilePreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *FilePreResponse) Reset() {
	*x = FilePreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientTransform_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilePreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePreResponse) ProtoMessage() {}

func (x *FilePreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clientTransform_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePreResponse.ProtoReflect.Descriptor instead.
func (*FilePreResponse) Descriptor() ([]byte, []int) {
	return file_clientTransform_proto_rawDescGZIP(), []int{3}
}

func (x *FilePreResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *FilePreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FilePostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *FilePostResponse) Reset() {
	*x = FilePostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientTransform_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePostResponse) ProtoMessage() {}

func (x *FilePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clientTransform_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePostResponse.ProtoReflect.Descriptor instead.
func (*FilePostResponse) Descriptor() ([]byte, []int) {
	return file_clientTransform_proto_rawDescGZIP(), []int{4}
}

func (x *FilePostResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *FilePostResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_clientTransform_proto protoreflect.FileDescriptor

var file_clientTransform_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x55, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b,
	0x66, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0b, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x81,
	0x01, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x37, 0x0a,
	0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x17, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x55,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x55,
	0x49, 0x44, 0x22, 0x9b, 0x01, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x44, 0x12, 0x37, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x4b, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4c, 0x0a,
	0x10, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x20, 0x0a, 0x0a, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x4f, 0x43,
	0x41, 0x4c, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x50, 0x49, 0x10, 0x01, 0x32, 0xbe, 0x01,
	0x0a, 0x11, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x13, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x50, 0x72, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1b, 0x2e, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x14, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x1c, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2e,
	0x5a, 0x2c, 0x4e, 0x65, 0x6b, 0x6f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clientTransform_proto_rawDescOnce sync.Once
	file_clientTransform_proto_rawDescData = file_clientTransform_proto_rawDesc
)

func file_clientTransform_proto_rawDescGZIP() []byte {
	file_clientTransform_proto_rawDescOnce.Do(func() {
		file_clientTransform_proto_rawDescData = protoimpl.X.CompressGZIP(file_clientTransform_proto_rawDescData)
	})
	return file_clientTransform_proto_rawDescData
}

var file_clientTransform_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clientTransform_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_clientTransform_proto_goTypes = []interface{}{
	(ClientType)(0),          // 0: clientProto.ClientType
	(*FileData)(nil),         // 1: clientProto.FileData
	(*FilePreRequest)(nil),   // 2: clientProto.FilePreRequest
	(*FilePostRequest)(nil),  // 3: clientProto.FilePostRequest
	(*FilePreResponse)(nil),  // 4: clientProto.FilePreResponse
	(*FilePostResponse)(nil), // 5: clientProto.FilePostResponse
}
var file_clientTransform_proto_depIdxs = []int32{
	0, // 0: clientProto.FilePreRequest.clientType:type_name -> clientProto.ClientType
	0, // 1: clientProto.FilePostRequest.clientType:type_name -> clientProto.ClientType
	1, // 2: clientProto.FilePostRequest.localData:type_name -> clientProto.FileData
	2, // 3: clientProto.FileUploadService.HandleFilePreUpload:input_type -> clientProto.FilePreRequest
	3, // 4: clientProto.FileUploadService.HandleFilePostUpload:input_type -> clientProto.FilePostRequest
	4, // 5: clientProto.FileUploadService.HandleFilePreUpload:output_type -> clientProto.FilePreResponse
	5, // 6: clientProto.FileUploadService.HandleFilePostUpload:output_type -> clientProto.FilePostResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_clientTransform_proto_init() }
func file_clientTransform_proto_init() {
	if File_clientTransform_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clientTransform_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientTransform_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilePreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientTransform_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientTransform_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilePreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientTransform_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilePostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clientTransform_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clientTransform_proto_goTypes,
		DependencyIndexes: file_clientTransform_proto_depIdxs,
		EnumInfos:         file_clientTransform_proto_enumTypes,
		MessageInfos:      file_clientTransform_proto_msgTypes,
	}.Build()
	File_clientTransform_proto = out.File
	file_clientTransform_proto_rawDesc = nil
	file_clientTransform_proto_goTypes = nil
	file_clientTransform_proto_depIdxs = nil
}
